base_images:
  ansible:
    name: "4.20"
    namespace: ocp
    tag: ansible
  aws-efs-csi-operator-create-efs:
    name: "4.20"
    namespace: ocp
    tag: aws-efs-csi-operator-create-efs
  cli:
    name: "4.20"
    namespace: ocp
    tag: cli
  cli-ocm:
    name: cli-ocm
    namespace: ci
    tag: latest
  cluster-api-actuator-pkg-test:
    name: cluster-api-actuator-pkg-test
    namespace: ci
    tag: "4.20"
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  hypershift-operator:
    name: hypershift-operator
    namespace: hypershift
    tag: latest
  hypershift-tests:
    name: hypershift-tests
    namespace: hypershift
    tag: latest
  nested-environment-builder:
    name: nested-environment-builder
    namespace: ci
    tag: latest
  openstack-installer:
    name: "4.20"
    namespace: ocp
    tag: openstack-installer
  operator-sdk-mto:
    name: operator-sdk-mto
    namespace: origin
    tag: main
  rosa-aws-cli:
    name: rosa-aws-cli
    namespace: ci
    tag: release
  tests-private:
    name: tests-private
    namespace: ci
    tag: "4.20"
  tests-private-burner:
    name: tests-private-burner
    namespace: ci
    tag: "4.20"
  tests-private-postupg:
    name: tests-private
    namespace: ci
    tag: "4.20"
  tests-private-preupg:
    name: tests-private
    namespace: ci
    tag: "4.20"
  tests-private-ui:
    name: tests-private-ui
    namespace: ci
    tag: "4.20"
  tools:
    name: "4.20"
    namespace: ocp
    tag: tools
  upi-installer:
    name: "4.20"
    namespace: ocp
    tag: upi-installer
  verification-tests:
    name: verification-tests
    namespace: ci
    tag: latest
  vsphere-ci-python:
    name: vsphere-python
    namespace: ci
    tag: latest
releases:
  latest:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.20"
  multi-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.20"
  target:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.20"
resources:
  '*':
    limits:
      memory: 8Gi
    requests:
      cpu: "1"
      memory: 1Gi
tests:
- as: azure-ipi-confidentialvm-vmgueststateonly-mini-perm-f7
  cron: 9 1 6,15,22,29 * *
  steps:
    cluster_profile: azure-confidential-qe
    env:
      AZURE_INSTALL_USE_MINIMAL_PERMISSIONS: "yes"
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      COMPUTE_CUSTOM_AZURE_AZ: '[''2'']'
      CP_CUSTOM_AZURE_AZ: '[''2'']'
      COMPUTE_NODE_TYPE: Standard_EC4es_v6
      CONTROL_PLANE_INSTANCE_TYPE: Standard_EC4es_v6
      ENABLE_CONFIDENTIAL_COMPUTE: "true"
      ENABLE_CONFIDENTIAL_CONTROL_PLANE: "true"
      ENABLE_ENCRYPTIONATHOST_CONTROL_PLANE: "false"
    test:
    - chain: openshift-e2e-test-qe
    workflow: cucushift-installer-rehearse-azure-ipi-confidential-confidentialvm
